name: smarthomex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5
  http: ^1.5.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.1
  flutter_svg: ^2.2.0

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2
  mqtt_client: ^10.10.0

  # Video playback
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/certificates/emqxsl-ca.crt
    - assets/videos/smarthomex_intro.mp4